import re

file_path = r'app\src\main\java\com\example\notecalc\MainActivity.java'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

search = '''        canvas.drawText("Generated by NoteCalc  \u2022  " + lastMod + "  \u2022  Page " + pageNum, margin, y + 12f, subPaint);

        document.finishPage(page);
        pageTracker[0] = pageNum;
    }'''

if search in content:
    # it shouldn't be there because I removed it, but let's check
    pass
else:
    # Let's find exactly what is there
    pass
