import re

file_path = r'app\src\main\java\com\example\notecalc\MainActivity.java'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Replace the records sorting and initialization
search_records = '''        // Copy and sort the records chronologically to prevent jumbled PDFs
        List<Record> records = new ArrayList<>(account.getRecords());
        java.util.Collections.sort(records, new java.util.Comparator<Record>() {
            @Override
            public int compare(Record r1, Record r2) {
                return Integer.compare(r1.getOriginalIndex(), r2.getOriginalIndex());
            }
        });'''
        
replace_records = '''        // Copy and sort the records chronologically to prevent jumbled PDFs
        List<Record> expRecords = new ArrayList<>(account.getRecords());
        java.util.Collections.sort(expRecords, new java.util.Comparator<Record>() {
            @Override
            public int compare(Record r1, Record r2) {
                return Integer.compare(r1.getOriginalIndex(), r2.getOriginalIndex());
            }
        });
        
        List<Record> budRecords = new ArrayList<>(account.getBudgetRecords());
        java.util.Collections.sort(budRecords, new java.util.Comparator<Record>() {
            @Override
            public int compare(Record r1, Record r2) {
                return Integer.compare(r1.getOriginalIndex(), r2.getOriginalIndex());
            }
        });
        
        List<List<Record>> allRecordLists = new ArrayList<>();
        List<String> listNames = new ArrayList<>();
        List<Double> listTotals = new ArrayList<>();
        
        if (!expRecords.isEmpty() || budRecords.isEmpty()) {
            allRecordLists.add(expRecords);
            listNames.add(budRecords.isEmpty() ? null : "Expenses");
            listTotals.add(account.calculateTotal());
        }
        if (!budRecords.isEmpty()) {
            allRecordLists.add(budRecords);
            listNames.add("Budgets");
            listTotals.add(account.calculateTotalBudget());
        }'''
content = content.replace(search_records, replace_records)

# Replace the subtitle records.size() with expRecords.size() + budRecords.size()
search_subtitle = '''String subtitle = "Last modified: " + lastMod + "  |  Items: " + records.size();'''
replace_subtitle = '''String subtitle = "Last modified: " + lastMod + "  |  Items: " + (expRecords.size() + budRecords.size());'''
content = content.replace(search_subtitle, replace_subtitle)


# Now wrap the table rendering block
search_table_start = '''        // --- Draw table header row ---
        float hx = margin;'''

replace_table_start = '''        for (int listIdx = 0; listIdx < allRecordLists.size(); listIdx++) {
            List<Record> records = allRecordLists.get(listIdx);
            String tableName = listNames.get(listIdx);
            double totalAmt = listTotals.get(listIdx);
            
            if (tableName != null) {
                if (y + 50f > bottomLimit) {
                    document.finishPage(page);
                    pageNum++;
                    pageInfo = new PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create();
                    page = document.startPage(pageInfo);
                    canvas = page.getCanvas();
                    canvas.drawRect(0, 0, pageWidth, pageHeight, bgPaint);
                    y = margin;
                }
                y += 10f;
                canvas.drawText(tableName, margin, y + 15f, titlePaint);
                y += 25f;
            }

        // --- Draw table header row ---
        float hx = margin;'''

content = content.replace(search_table_start, replace_table_start)

# Now fix the total row string calculation
search_total = '''        canvas.drawText("TOTAL", margin + 4, y + 15f, totalTextPaint);
        String totalStr = String.format(Locale.getDefault(), "%.2f", account.calculateTotal());'''
        
replace_total = '''        canvas.drawText("TOTAL", margin + 4, y + 15f, totalTextPaint);
        String totalStr = String.format(Locale.getDefault(), "%.2f", totalAmt);'''
content = content.replace(search_total, replace_total)

# And close the loop right before footer
search_footer = '''        // --- Footer ---
        canvas.drawText("Generated by NoteCalc  \u2022  " + lastMod + "  \u2022  Page " + pageNum, margin, y + 12f, subPaint);'''

replace_footer = '''        } // End of tables loop

        // --- Footer ---
        // Need to check if footer fits
        if (y + 20f > bottomLimit) {
            document.finishPage(page);
            pageNum++;
            pageInfo = new PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNum).create();
            page = document.startPage(pageInfo);
            canvas = page.getCanvas();
            canvas.drawRect(0, 0, pageWidth, pageHeight, bgPaint);
            y = margin;
        }
        canvas.drawText("Generated by NoteCalc  \u2022  " + lastMod + "  \u2022  Page " + pageNum, margin, y + 12f, subPaint);'''
        
content = content.replace(search_footer, replace_footer)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
print("PDF logic refactored")
