package com.example.notecalc.pdf;

import android.graphics.pdf.PdfDocument;
import com.example.notecalc.AppUtils;
import com.example.notecalc.MainActivity;
import com.example.notecalc.Record;
import java.util.LinkedHashMap;
import java.util.List;

public class PdfDocumentRenderer {

    public static void renderDocument(MainActivity activity, PdfDocument document, PdfThemeHelper.PdfTheme theme, 
                                      String titleText, String subtitle, String footerLastMod, 
                                      List<List<Record>> allRecordLists, List<String> listNames, 
                                      List<Double> listTotals, String accountTitle, int[] pageTracker) {
                                          
        int contentWidth = theme.pageWidth - theme.margin * 2;
        float bottomLimit = theme.pageHeight - theme.margin;

        float colSno    = 38f;
        float colDate   = 70f;
        float colTime   = 55f;
        float colAmount = 60f;
        float colDesc   = contentWidth - colSno - colDate - colTime - colAmount;
        float rowHeight = 22f;

        PdfPageHelper.PdfState state = new PdfPageHelper.PdfState();
        state.pageNum = pageTracker[0];
        PdfPageHelper.startNewPage(document, state, theme);

        float titleLineHeight = 28f;
        float maxTitleWidth = contentWidth - 15f;
        List<String> titleLines = AppUtils.wrapText(titleText, theme.titlePaint, maxTitleWidth);
        for (String line : titleLines) {
            state.canvas.drawText(line, theme.margin, state.y + 22f, theme.titlePaint);
            state.y += titleLineHeight;
        }
        state.y += 4f;

        state.canvas.drawText(subtitle, theme.margin, state.y + 13f, theme.subPaint);
        state.y += 20f;

        state.canvas.drawLine(theme.margin, state.y + 4f, theme.pageWidth - theme.margin, state.y + 4f, theme.dividerPaint);
        state.y += 16f;

        for (int listIdx = 0; listIdx < allRecordLists.size(); listIdx++) {
            List<Record> records = allRecordLists.get(listIdx);
            String tableName = listNames.get(listIdx);
            double totalAmt = listTotals.get(listIdx);
            
            PdfTableHelper.drawRecordTable(document, state, theme, records, tableName, totalAmt, accountTitle, colSno, colDate, colTime, colAmount, colDesc, rowHeight);
        }

        if (state.y + 20f > bottomLimit) {
            PdfPageHelper.startNewPage(document, state, theme);
        }
        state.canvas.drawText("Generated by NoteCalc  •  " + footerLastMod + "  •  Page " + state.pageNum, theme.margin, state.y + 12f, theme.subPaint);

        document.finishPage(state.page);
        pageTracker[0] = state.pageNum;

        LinkedHashMap<Record, String> recordLabels = new LinkedHashMap<>();
        for (int listIdx = 0; listIdx < allRecordLists.size(); listIdx++) {
            List<Record> list = allRecordLists.get(listIdx);
            String prefix = listNames.get(listIdx) != null ? listNames.get(listIdx) + " - " : "";
            for (int j = 0; j < list.size(); j++) {
                recordLabels.put(list.get(j), prefix + "S.No " + (j + 1) + ": " + list.get(j).getDescription());
            }
        }
        PdfAppendixHelper.appendAttachmentsAppendixToPdf(activity, document, recordLabels, pageTracker);
    }
}
