package com.example.notecalc.pdf;

import android.graphics.pdf.PdfDocument;
import com.example.notecalc.Account;
import com.example.notecalc.AppUtils;
import com.example.notecalc.MainActivity;
import com.example.notecalc.Record;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;

public class PdfRenderHelper {

    public static void appendAccountToPdf(MainActivity activity, PdfDocument document, Account account, int[] pageTracker, PdfSortOrder sortOrder) {
        PdfThemeHelper.PdfTheme theme = new PdfThemeHelper.PdfTheme(activity);
        
        int contentWidth = theme.pageWidth - theme.margin * 2;
        float bottomLimit = theme.pageHeight - theme.margin;

        float colSno    = 38f;
        float colDate   = 70f;
        float colTime   = 55f;
        float colAmount = 60f;
        float colDesc   = contentWidth - colSno - colDate - colTime - colAmount;
        float rowHeight = 22f;

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
        String lastMod = sdf.format(new Date(account.getLastModified()));
        
        List<Record> expRecords = new ArrayList<>(account.getRecords());
        PdfSortHelper.sortRecords(expRecords, sortOrder);
        
        List<Record> budRecords = new ArrayList<>(account.getBudgetRecords());
        PdfSortHelper.sortRecords(budRecords, sortOrder);
        
        List<List<Record>> allRecordLists = new ArrayList<>();
        List<String> listNames = new ArrayList<>();
        List<Double> listTotals = new ArrayList<>();
        
        if (!budRecords.isEmpty()) {
            allRecordLists.add(budRecords);
            listNames.add("Budgets");
            double bt = 0; for(Record r: budRecords) bt += r.getAmount();
            listTotals.add(bt);
        }
        if (!expRecords.isEmpty() || budRecords.isEmpty()) {
            allRecordLists.add(expRecords);
            listNames.add(budRecords.isEmpty() ? null : "Expenses");
            listTotals.add(account.calculateTotal());
        }

        PdfTableHelper.PdfState state = new PdfTableHelper.PdfState();
        state.pageNum = pageTracker[0] + 1;
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(theme.pageWidth, theme.pageHeight, state.pageNum).create();
        state.page = document.startPage(pageInfo);
        state.canvas = state.page.getCanvas();
        state.canvas.drawRect(0, 0, theme.pageWidth, theme.pageHeight, theme.bgPaint);
        state.y = theme.margin;

        String titleText = account.getTitle();
        float titleLineHeight = 28f;
        float maxTitleWidth = contentWidth - 15f;
        List<String> titleLines = AppUtils.wrapText(titleText, theme.titlePaint, maxTitleWidth);
        for (String line : titleLines) {
            state.canvas.drawText(line, theme.margin, state.y + 22f, theme.titlePaint);
            state.y += titleLineHeight;
        }
        state.y += 4f;

        String subtitle = "Last modified: " + lastMod + "  |  Items: " + (expRecords.size() + budRecords.size());
        double budget = account.calculateTotalBudget();
        if (budget > 0) {
            subtitle += "  |  Budget: " + String.format(Locale.getDefault(), "%.2f", budget);
        }
        state.canvas.drawText(subtitle, theme.margin, state.y + 13f, theme.subPaint);
        state.y += 20f;

        state.canvas.drawLine(theme.margin, state.y + 4f, theme.pageWidth - theme.margin, state.y + 4f, theme.dividerPaint);
        state.y += 16f;

        for (int listIdx = 0; listIdx < allRecordLists.size(); listIdx++) {
            List<Record> records = allRecordLists.get(listIdx);
            String tableName = listNames.get(listIdx);
            double totalAmt = listTotals.get(listIdx);
            
            PdfTableHelper.drawRecordTable(document, state, theme, records, tableName, totalAmt, account.getTitle(), colSno, colDate, colTime, colAmount, colDesc, rowHeight);
        }

        if (state.y + 20f > bottomLimit) {
            document.finishPage(state.page);
            state.pageNum++;
            PdfDocument.PageInfo pi = new PdfDocument.PageInfo.Builder(theme.pageWidth, theme.pageHeight, state.pageNum).create();
            state.page = document.startPage(pi);
            state.canvas = state.page.getCanvas();
            state.canvas.drawRect(0, 0, theme.pageWidth, theme.pageHeight, theme.bgPaint);
            state.y = theme.margin;
        }
        state.canvas.drawText("Generated by NoteCalc  •  " + lastMod + "  •  Page " + state.pageNum, theme.margin, state.y + 12f, theme.subPaint);

        document.finishPage(state.page);
        pageTracker[0] = state.pageNum;

        LinkedHashMap<Record, String> recordLabels = new LinkedHashMap<>();
        for (int listIdx = 0; listIdx < allRecordLists.size(); listIdx++) {
            List<Record> list = allRecordLists.get(listIdx);
            String prefix = listNames.get(listIdx) != null ? listNames.get(listIdx) + " - " : "";
            for (int j = 0; j < list.size(); j++) {
                recordLabels.put(list.get(j), prefix + "S.No " + (j + 1) + ": " + list.get(j).getDescription());
            }
        }
        PdfAppendixHelper.appendAttachmentsAppendixToPdf(activity, document, recordLabels, pageTracker);
    }

    public static void appendSelectedRecordsToPdf(MainActivity activity, PdfDocument document, Account account, List<Record> selectedRecords, int[] pageTracker, PdfSortOrder sortOrder) {
        PdfThemeHelper.PdfTheme theme = new PdfThemeHelper.PdfTheme(activity);

        int contentWidth = theme.pageWidth - theme.margin * 2;
        float bottomLimit = theme.pageHeight - theme.margin;

        float colSno    = 38f;
        float colDate   = 70f;
        float colTime   = 55f;
        float colAmount = 60f;
        float colDesc   = contentWidth - colSno - colDate - colTime - colAmount;
        float rowHeight = 22f;

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
        String lastMod = sdf.format(new Date(account.getLastModified()));
        
        List<Record> recordsToPrint = new ArrayList<>(selectedRecords);
        PdfSortHelper.sortRecords(recordsToPrint, sortOrder);
        
        double totalAmt = 0;
        for (Record r : recordsToPrint) totalAmt += r.getAmount();

        PdfTableHelper.PdfState state = new PdfTableHelper.PdfState();
        state.pageNum = pageTracker[0] + 1;
        PdfDocument.PageInfo pageInfo = new PdfDocument.PageInfo.Builder(theme.pageWidth, theme.pageHeight, state.pageNum).create();
        state.page = document.startPage(pageInfo);
        state.canvas = state.page.getCanvas();
        state.canvas.drawRect(0, 0, theme.pageWidth, theme.pageHeight, theme.bgPaint);
        state.y = theme.margin;

        String titleText = account.getTitle() + " (Selected)";
        float titleLineHeight = 28f;
        float maxTitleWidth = contentWidth - 15f;
        List<String> titleLines = AppUtils.wrapText(titleText, theme.titlePaint, maxTitleWidth);
        for (String line : titleLines) {
            state.canvas.drawText(line, theme.margin, state.y + 22f, theme.titlePaint);
            state.y += titleLineHeight;
        }
        state.y += 4f;

        String subtitle = "Exported: " + sdf.format(new Date()) + "  |  Items: " + recordsToPrint.size();
        state.canvas.drawText(subtitle, theme.margin, state.y + 13f, theme.subPaint);
        state.y += 20f;

        state.canvas.drawLine(theme.margin, state.y + 4f, theme.pageWidth - theme.margin, state.y + 4f, theme.dividerPaint);
        state.y += 16f;

        PdfTableHelper.drawRecordTable(document, state, theme, recordsToPrint, null, totalAmt, account.getTitle(), colSno, colDate, colTime, colAmount, colDesc, rowHeight);

        if (state.y + 20f > bottomLimit) {
            document.finishPage(state.page);
            state.pageNum++;
            PdfDocument.PageInfo pi = new PdfDocument.PageInfo.Builder(theme.pageWidth, theme.pageHeight, state.pageNum).create();
            state.page = document.startPage(pi);
            state.canvas = state.page.getCanvas();
            state.canvas.drawRect(0, 0, theme.pageWidth, theme.pageHeight, theme.bgPaint);
            state.y = theme.margin;
        }
        state.canvas.drawText("Generated by NoteCalc  •  " + lastMod + "  •  Page " + state.pageNum, theme.margin, state.y + 12f, theme.subPaint);

        document.finishPage(state.page);
        pageTracker[0] = state.pageNum;

        LinkedHashMap<Record, String> recordLabels = new LinkedHashMap<>();
        for (int j = 0; j < recordsToPrint.size(); j++) {
            recordLabels.put(recordsToPrint.get(j), "S.No " + (j + 1) + ": " + recordsToPrint.get(j).getDescription());
        }
        PdfAppendixHelper.appendAttachmentsAppendixToPdf(activity, document, recordLabels, pageTracker);
    }
}
